name: Apply changes

concurrency:
  # Wait for other workflows to finish before starting this one
  group: ${{ github.repository_id }}
  cancel-in-progress: false 

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  apply:
    name: Apply changes
    runs-on: ubuntu-latest
    env:
        DOMAIN_NAME: ${{ vars.DOMAIN_NAME }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get private key from secrets
        run: echo "${{ secrets.PRIVATE_KEY }}" > private.key

      - name: Get Contabo YAML from secrets && install cntb
        run: |
          echo "${{ secrets.CNTB_YAML_B64 }}" | base64 -d > ~/.cntb.yaml
          curl -sL https://github.com/contabo/cntb/releases/download/v1.5.3/cntb_v1.5.3_linux_amd64.tar.gz | tar xz -C /usr/local/bin cntb 
          chmod +x /usr/local/bin/cntb

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Apply changes
        run: make apply
