name: Apply changes 

concurrency:
  group: ${{ github.repository_id }} 
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get private key from secrets
        run: echo "${{ secrets.PRIVATE_KEY }}" > private.key

      - name: Apply changes
        run: make upgrade
